### ISSUE TITLE
Sometimes quotas are reported as over 100% utilization

### ISSUE THREAD

**Issue by bgood** [google/quota-monitoring-solution#18]
Sometimes QMS will report quotas as over 100% utilization. However, looking in the GCP UI we are not able to identify those quotas.

**Comment by kjwinters** [comment]
+1  customers have had to validate QMS data

**Comment by kjwinters** [comment]
specific quotas show +100% utilization are:

RecommendLocationsRequestsPerMinutePerProject
NetworkEndpointListRequestsPerMinutePerProject
INTERCONNECT-TOTAL-GBPS-per-project
GetSerialPortOutputRequestsPerMinutePerProject

**Comment by anuradha-bajpai-google** [comment]
Hi @kjwinters  Thanks for providing the additional details. As discussed, this is a [known limitation](https://github.com/google/quota-monitoring-solution#known-limitations) as we mentioned on the deployment guide:

- Out of the box solution is configured to scan quotas ‘once every day’. The SQL query to build the dashboard uses current date and hour to filter the records. The records are grouped by hour. If you change the frequency, make changes to the query to rightly reflect the latest data.

If the frequency is higher than 1 hour, changes in the SQL query is needed that is used to build the Dashboard.

We are working on fixing this limitation and will update this thread soon. Thanks again!

Thanks,
Anuradha
