### ISSUE TITLE
Cloud Functions error logging

### ISSUE THREAD

**Issue by anuradha-bajpai-google** [google/quota-monitoring-solution#31]
Customer noticed that Cloud Functions quotaMonitoringListProjects and quotaMonitoringScanProjects generate plenty (thousands) of unneccessary logs. 

Can we disable it? Any reasons for those functions to run? For Customer, they are not needed and generate too much noise in the logs 

Failed to find a usable hardware address from the network interfaces; using random bytes: ba:61:09:1a:36:5a:d6:16. 

"Function invocation was interrupted. Error: function terminated. Recommended action: inspect logs for termination reason. Additional troubleshooting documentation can be found at https://cloud.google.com/functions/docs/troubleshooting#logging "
"Compute Engine API has not been used in project 698303822038 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=698303822038 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry."
"The request was aborted because there was no available instance. Additional troubleshooting documentation can be found at: https://cloud.google.com/functions/docs/troubleshooting#scalability"

**Comment by bgood** [comment]
@ypenn21 Thanks for taking care of this issue!
